### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/xaph/imdb.sql'

### ISSUE THREAD

**Issue by sollarman** [dedeler/imdb-data-parser#32]
Getting this error, path related.

Traceback (most recent call last):
  File "./imdbparser.py", line 85, in <module>
    ParsingHelper.parse_all(preferencesMap)
  File "/Users/sollarman/imdb-data-parser/idp/parser/parsinghelper.py", line 60, in parse_all
    ParsingHelper.parse_one(item, preferencesMap)
  File "/Users/sollarman/imdb-data-parser/idp/parser/parsinghelper.py", line 49, in parse_one
    parser = ParserClass(preferencesMap)
  File "/Users/sollarman/imdb-data-parser/idp/parser/moviesparser.py", line 56, in **init**
    self.f = open("/home/xaph/imdb.sql", "w", encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: '/home/xaph/imdb.sql'

**Comment by xaph** [comment]
Hi sollarman,

I've pushed an unstable changes to repository last night (https://github.com/dedeler/imdb-data-parser/commit/ef4c6c02e72075cc8bd7f4c0e5bc88eb125904d9)

Today, I changed static paths to config paths with last commit(https://github.com/dedeler/imdb-data-parser/commit/75cee996e62e79355536ed5cbf799998edc7dcbf)

Can you try it again?

**Comment by sollarman** [comment]
Alright, works now

Zhenya Kuzmischenko

---

aurra systems
www.aurra.net
Business: www.twitter.com/aurranet
Personal:  www.twitter.com/sollarman
