### ISSUE TITLE
"No such file or directory" error on windows 8.1

### ISSUE THREAD

**Issue by tugberkugurlu** [dedeler/imdb-data-parser#38]
I'm trying to run this on windows 8.1 and I am having problems. Here is my settings.py file:

```
    INPUT_DIR = "/d/apps/temp/inputs"
    OUTPUT_DIR = "/d/apps/temp/outputs"

    INTERFACES_SERVER = "ftp.fu-berlin.de"
    INTERFACES_DIRECTORY = "pub/misc/movies/database/"
    #alternative servers:
    #ftp://ftp.funet.fi/pub/mirrors/ftp.imdb.com/pub/
    #ftp://ftp.sunet.se/pub/tv+movies/imdb/

    LISTS = [
            "directors",
            "genres",
            "movies",
            "plot",
            "actors", 
            "actresses",
            "aka-names",
            "aka-titles",
            "ratings"
    ]
```

"/d/apps/temp/inputs" and "/d/apps/temp/outputs" folders exist in my machine. When I run the `imdbparser.py -u`, I'm getting the following output with errors:

```
INFO - mode:TSV
INFO - input_dir:/d/apps/temp/inputs
INFO - output_dir:/d/apps/temp/outputs\2014-06-29_135758_ImdbParserOutput
INFO - update_lists:True
INFO - Downloading IMDB dumps, this may take a while depending on your connection speed
INFO - Lists will downloaded from server:ftp.fu-berlin.de
INFO - Started to download list:directors
ERROR - There is a problem when downloading list directors
                [Errno 2] No such file or directory: '/d/apps/temp/inputs\\directors.list.gz'
INFO - Started to download list:genres
ERROR - There is a problem when downloading list genres
                [Errno 2] No such file or directory: '/d/apps/temp/inputs\\genres.list.gz'
INFO - Started to download list:movies
ERROR - There is a problem when downloading list movies
                [Errno 2] No such file or directory: '/d/apps/temp/inputs\\movies.list.gz'
INFO - Started to download list:plot
ERROR - There is a problem when downloading list plot
                [Errno 2] No such file or directory: '/d/apps/temp/inputs\\plot.list.gz'
INFO - Started to download list:actors
ERROR - There is a problem when downloading list actors
                [Errno 2] No such file or directory: '/d/apps/temp/inputs\\actors.list.gz'
INFO - Started to download list:actresses
ERROR - There is a problem when downloading list actresses
                [Errno 2] No such file or directory: '/d/apps/temp/inputs\\actresses.list.gz'
INFO - Started to download list:aka-names
ERROR - There is a problem when downloading list aka-names
                [Errno 2] No such file or directory: '/d/apps/temp/inputs\\aka-names.list.gz'
INFO - Started to download list:aka-titles
ERROR - There is a problem when downloading list aka-titles
                [Errno 2] No such file or directory: '/d/apps/temp/inputs\\aka-titles.list.gz'
INFO - Started to download list:ratings
ERROR - There is a problem when downloading list ratings
                [Errno 2] No such file or directory: '/d/apps/temp/inputs\\ratings.list.gz'
INFO - 0 lists are downloaded
INFO - Parsing, please wait. This may take very long time...
INFO - ___________________
INFO - Parsing directors...
INFO - Trying to find file: /d/apps/temp/inputs\directors.list
ERROR - File cannot be found: /d/apps/temp/inputs\directors.list
INFO - Trying to find file: /d/apps/temp/inputs\directors.list.gz
ERROR - File cannot be found: /d/apps/temp/inputs\directors.list.gz
Traceback (most recent call last):
    File "D:\Apps\imdb-data-parser\imdbparser.py", line 85, in <module>
        ParsingHelper.parse_all(preferences_map)
    File "D:\Apps\imdb-data-parser\idp\parser\parsinghelper.py", line 61, in parse_all
        ParsingHelper.parse_one(item, preferences_map)
    File "D:\Apps\imdb-data-parser\idp\parser\parsinghelper.py", line 50, in parse_one
        parser = ParserClass(preferences_map)
    File "D:\Apps\imdb-data-parser\idp\parser\directorsparser.py", line 59, in __init__
        super(DirectorsParser, self).__init__(preferences_map)
    File "D:\Apps\imdb-data-parser\idp\parser\baseparser.py", line 50, in __init__
        self.input_file = self.filehandler.get_input_file()
    File "D:\Apps\imdb-data-parser\idp\utils\filehandler.py", line 57, in get_input_file
        raise RuntimeError("FileNotFoundError: %s", full_file_path)
RuntimeError: ('FileNotFoundError: %s', '/d/apps/temp/inputs\\directors.list')
```

BTW, I'm running this on Python 3.4.1.

**Comment by demonshreder** [comment]
Same problem. Using linux here. 
I think that is cuz I don't have any files. Therefore the parser is just looking to 'update' not actually download them from scratch.
Would be nice if you could make it download if files ain't there, preferably after asking the user.

**Comment by iaravindreddyp** [comment]
mac os same problem here
